/**
 * Bahasa Melayu for the PUBLIC site (v1.32.0).
 *
 * CEO, 20-08-2026: "put a toggle for EN BM so that client can choose their
 * preferences" — and, asked how far it should go: every public page.
 *
 * The KEY is the exact English string as it is written in the source (in
 * constants/pages.ts, constants/content.ts, or straight in the JSX). That is
 * deliberate: the English copy stays the single source of truth, an entry
 * that falls out of date simply stops matching and the visitor sees English
 * rather than a stale translation, and adding copy never requires touching
 * two files in lockstep.
 *
 * Applied at runtime by components/live/lang-runtime.tsx — see that file for
 * why, and for what this deliberately does NOT do (BM is a reader
 * convenience; English remains the indexed language).
 */
export const MS_DICT: Record<string, string> = {
  "1 per week": "1 setiap minggu",
  "1. A hero offer. Not your whole catalogue — one deal strong enough to pin for the entire session. Viewers decide in seconds whether a live is worth staying for, and the pinned offer is what they judge.": "1. Satu hero offer. Bukan seluruh katalog anda — satu deal yang cukup kuat untuk di-pin sepanjang sesi. Penonton menentukan dalam beberapa saat sama ada sesuatu live itu berbaloi untuk ditonton, dan pinned offer itulah yang mereka nilai.",
  "2 assets / month": "2 aset / bulan",
  "2. Stock you can actually ship. Nothing damages a new live channel faster than selling what you can't deliver. Confirm quantities before the session, not during it.": "2. Stok yang benar-benar boleh dihantar. Tiada apa yang merosakkan channel live baharu lebih cepat daripada menjual barang yang anda tidak mampu hantar. Sahkan kuantiti sebelum sesi, bukan semasa sesi.",
  "3 per week": "3 setiap minggu",
  "5 things to prepare before your brand's first TikTok Live": "5 perkara yang perlu disediakan sebelum TikTok Live pertama jenama anda",
  "6 creative assets per month": "6 aset kreatif sebulan",
  "A premium modestwear label": "Sebuah label modestwear premium",
  "A scoped proposal with a fixed fee, the questions the engagement will answer, and the deliverables you keep.": "Cadangan berskop dengan yuran tetap, soalan yang akan dijawab oleh engagement ini, dan deliverable yang anda simpan.",
  "A2Z CREATIVE MARKETING is a Malaysian creative marketing group based in Johor Bahru. We build brands and then sell for them: creative marketing, digital marketing, content creation, live commerce, marketing consultancy, and business and product development — one team, one accountable plan.": "A2Z CREATIVE MARKETING ialah kumpulan pemasaran kreatif Malaysia yang berpangkalan di Johor Bahru. Kami bina jenama dan kemudian menjual untuk mereka: pemasaran kreatif, pemasaran digital, penghasilan content, live commerce, perundingan pemasaran, serta pembangunan perniagaan dan produk — satu pasukan, satu pelan yang bertanggungjawab.",
  "A2Z Creative Marketing is a Malaysian creative marketing group in Johor Bahru — creative and digital marketing, live commerce, content creation, marketing consultancy, business development, and product development for brands that want to grow.": "A2Z Creative Marketing ialah kumpulan pemasaran kreatif Malaysia di Johor Bahru — pemasaran kreatif dan digital, live commerce, penghasilan content, perundingan pemasaran, pembangunan perniagaan, dan pembangunan produk untuk jenama yang mahu berkembang.",
  "AZ ONE OFFICIAL — A Consultancy Service by A2Z Creative Marketing. Business consultation, live commerce consultancy, and brand and channel strategy for Malaysian brands, from operators who sell live every week.": "AZ ONE OFFICIAL — Perkhidmatan Perundingan oleh A2Z Creative Marketing. Perundingan perniagaan, perundingan live commerce, dan strategi jenama serta channel untuk jenama Malaysia, daripada operator yang menjual secara live setiap minggu.",
  "Approach": "Pendekatan",
  "Before you ask": "Sebelum anda bertanya",
  "Book a free consultation on WhatsApp": "Tempah konsultasi percuma di WhatsApp",
  "Brand identity, campaign concepts, and the visuals that carry them — covers, overlays, product cards, and key art that make a brand worth stopping the scroll for.": "Identiti jenama, konsep campaign, dan visual yang membawanya — cover, overlay, kad produk, dan key art yang buat sesebuah jenama berbaloi untuk hentikan scroll.",
  "Build": "Bina",
  "Built the live selling channel from a standing start: session format, trained hosts, rundowns, and the creative that surrounds each drop.": "Membina channel live selling dari kosong: format sesi, host terlatih, rundown, dan kreatif yang mengelilingi setiap drop.",
  "Campaigns, brands, and live sessions produced by A2Z Creative Marketing. Clients are shown anonymised unless they have given us permission to name them.": "Campaign, jenama, dan sesi live yang dihasilkan oleh A2Z Creative Marketing. Pelanggan dipaparkan tanpa nama melainkan mereka memberi kebenaran untuk kami menamakan mereka.",
  "Careers": "Kerjaya",
  "Changes": "Perubahan",
  "Common questions about A2Z Creative Marketing's services, packages, and how an engagement works.": "Soalan lazim tentang perkhidmatan, pakej, dan cara sesuatu engagement berjalan di A2Z Creative Marketing.",
  "Consultancy & business development": "Perundingan & pembangunan perniagaan",
  "Content & creative — short-form video editing, design, product styling": "Content & kreatif — editing video short-form, reka bentuk, styling produk",
  "Creative marketing": "Pemasaran kreatif",
  "Creative, digital, content, live commerce, and consultancy — pick a single lane or hand us the whole thing.": "Kreatif, digital, content, live commerce, dan perundingan — pilih satu lane atau serahkan semuanya kepada kami.",
  "Custom reporting to your format": "Reporting custom mengikut format anda",
  "Data we collect": "Data yang kami kumpul",
  "Dedicated live operations": "Operasi live yang dedicated",
  "Do you only do live commerce?": "Adakah anda buat live commerce sahaja?",
  "Follow @azoneofficialhq so our next session lands in your feed.": "Follow @azoneofficialhq supaya sesi kami yang seterusnya muncul dalam feed anda.",
  "Four steps. The order matters — each one feeds the next.": "Empat langkah. Urutannya penting — setiap satu menyuap yang seterusnya.",
  "Full session management: rundown, offers, order push": "Pengurusan sesi penuh: rundown, offer, order push",
  "Go to market": "Ke pasaran",
  "How A2Z Creative Marketing collects, uses, and protects your personal data.": "Bagaimana A2Z Creative Marketing mengumpul, menggunakan, dan melindungi data peribadi anda.",
  "How long is a live session, and how long before I see results?": "Berapa lama satu sesi live, dan berapa lama sebelum saya nampak hasilnya?",
  "How we use your data": "Cara kami menggunakan data anda",
  "Intellectual property": "Harta intelek",
  "Johor Bahru based team": "Pasukan berpangkalan di Johor Bahru",
  "Liability": "Liabiliti",
  "Live commerce is simple to describe and hard to fake: a host presents products on a live stream, viewers ask questions in real time, and purchases happen inside the same app — most often TikTok in Malaysia. No waiting, no guessing about sizing or texture, no leaving the video to check out.": "Live commerce mudah diterangkan tetapi susah dilakon-lakonkan: seorang host mempersembahkan produk dalam live stream, penonton bertanya soalan secara real time, dan pembelian berlaku dalam app yang sama — paling kerap TikTok di Malaysia. Tiada menunggu, tiada teka-teki tentang saiz atau tekstur, tiada perlu keluar dari video untuk checkout.",
  "Live commerce, in session": "Live commerce, dalam sesi",
  "Live hosts — confident on camera in Bahasa Melayu, English, or both": "Host live — yakin di depan kamera dalam Bahasa Melayu, English, atau kedua-duanya",
  "Local Malaysian team": "Pasukan tempatan Malaysia",
  "Marketing, run like a business — not an experiment": "Pemasaran, dijalankan seperti sebuah perniagaan — bukan satu eksperimen",
  "Monthly strategy call": "Panggilan strategi bulanan",
  "New product lines, bundle and range planning, and market-entry work for brands moving into a category or a channel for the first time — taken from idea to a plan someone can execute.": "Barisan produk baharu, perancangan bundle dan range, serta kerja kemasukan pasaran untuk jenama yang memasuki sesuatu kategori atau channel buat kali pertama — dibawa daripada idea kepada pelan yang boleh dilaksanakan.",
  "No. Live commerce is one of our strongest capabilities — we build and run live selling channels end to end — but it sits alongside brand and campaign creative, digital marketing, content production, and consultancy. If live is not right for your product, we will tell you and recommend what is.": "Tidak. Live commerce ialah salah satu kekuatan terbesar kami — kami bina dan jalankan channel live selling dari hujung ke hujung — tetapi ia berdiri seiring dengan kreatif jenama dan campaign, pemasaran digital, penghasilan content, dan perundingan. Jika live tidak sesuai untuk produk anda, kami akan beritahu dan cadangkan apa yang sesuai.",
  "On request": "Atas permintaan",
  "Onboarding consultation": "Konsultasi onboarding",
  "Operators, not observers": "Operator, bukan pemerhati",
  "Our consultancy work is delivered by AZ ONE OFFICIAL — A Consultancy Service by A2Z Creative Marketing — the business unit that advises brand owners on positioning, channel strategy, and live commerce. Same team, same standards, a dedicated remit.": "Kerja perundingan kami dikendalikan oleh AZ ONE OFFICIAL — Perkhidmatan Perundingan oleh A2Z Creative Marketing — unit perniagaan yang menasihati pemilik jenama tentang positioning, strategi channel, dan live commerce. Pasukan yang sama, standard yang sama, tugas yang khusus.",
  "Our services": "Perkhidmatan kami",
  "Pick the level of support you need": "Pilih tahap sokongan yang anda perlukan",
  "Post-live report: GMV, viewers, conversion, next actions": "Laporan pasca-live: GMV, viewers, conversion, tindakan seterusnya",
  "Practical notes on live commerce in Malaysia — what we learn running sessions, written for brand owners.": "Nota praktikal tentang live commerce di Malaysia — apa yang kami pelajari daripada menjalankan sesi, ditulis untuk pemilik jenama.",
  "Process": "Proses",
  "Reach, GMV, viewers, and conversion in plain numbers — plus what we'll change next month.": "Reach, GMV, viewers, dan conversion dalam angka yang jelas — serta apa yang akan kami ubah bulan depan.",
  "SSM-registered": "Berdaftar dengan SSM",
  "See all questions": "Lihat semua soalan",
  "Sell it live.": "Jual secara live.",
  "Sessions typically run 2–3 hours; shorter than that rarely gives the room time to build. On results: a first session gives you a baseline, not a verdict. Brands that commit to a consistent weekly schedule usually see the picture clearly within 4–6 weeks, because live rewards repetition more than one-off effort.": "Sesi biasanya berjalan 2–3 jam; lebih pendek daripada itu jarang memberi masa untuk momentum terbina. Tentang hasil: sesi pertama memberi anda baseline, bukan keputusan muktamad. Jenama yang komited pada jadual mingguan yang konsisten biasanya nampak gambaran sebenar dalam masa 4–6 minggu, kerana live memberi ganjaran kepada pengulangan lebih daripada usaha sekali sekala.",
  "Terms & Conditions": "Terma & Syarat",
  "That changes the advice. We know what a two-hour session actually costs to staff, how long a host takes to become good, what a realistic conversion rate looks like in month one versus month six, and which platform promises quietly do not hold. You get the version we would act on ourselves.": "Itu mengubah nasihat yang kami beri. Kami tahu berapa kos sebenar untuk staffing sesi dua jam, berapa lama seorang host mengambil masa untuk menjadi bagus, apa rupa conversion rate yang realistik pada bulan pertama berbanding bulan keenam, dan janji platform yang mana secara senyap tidak menjadi. Anda dapat versi yang kami sendiri akan guna.",
  "The fastest way to reach us is WhatsApp — tell us about your brand and we'll recommend the right starting package. No commitment.": "Cara paling pantas untuk hubungi kami ialah WhatsApp — beritahu kami tentang jenama anda dan kami akan cadangkan pakej permulaan yang sesuai. Tiada komitmen.",
  "The work itself — sessions with you and your team, our own research, and access to our operators where relevant.": "Kerja itu sendiri — sesi bersama anda dan pasukan anda, penyelidikan kami sendiri, dan akses kepada operator kami di mana berkaitan.",
  "To respond to your enquiries and provide our services.": "Untuk membalas pertanyaan anda dan menyediakan perkhidmatan kami.",
  "Training your in-house team on the selling techniques, session operations, and reporting rhythm our own team uses, so the capability stays with you when the engagement ends.": "Melatih pasukan dalaman anda tentang teknik jualan, operasi sesi, dan rentak reporting yang digunakan oleh pasukan kami sendiri, supaya keupayaan itu kekal dengan anda apabila engagement tamat.",
  "Watch how an A2Z live session comes together": "Tonton bagaimana sesi live A2Z terbentuk",
  "Watchers become buyers through offer structure — pinned deals, live pricing, limited quantities, and comment moderation that answers objections in the moment. Measured per session.": "Penonton bertukar menjadi pembeli melalui struktur offer — pinned deals, harga live, kuantiti terhad, dan moderasi komen yang menjawab keraguan pada masa itu juga. Diukur setiap sesi.",
  "We post constantly and nothing converts": "Kami post tanpa henti tetapi tiada yang convert",
  "We run the whole session: rundown, offers, moderation, order push, and post-live reporting. You watch the numbers.": "Kami jalankan keseluruhan sesi: rundown, offer, moderasi, order push, dan reporting pasca-live. Anda cuma pantau nombornya.",
  "Weekly reporting": "Reporting mingguan",
  "What do I need to prepare before the first live?": "Apa yang saya perlu sediakan sebelum live pertama?",
  "What it costs": "Berapa kosnya",
  "WhatsApp us here": "WhatsApp kami di sini",
  "Which platforms do you go live on?": "Platform apa yang anda gunakan untuk live?",
  "Yes, we run sessions from our own setup in Johor Bahru, including lighting and the streaming setup. If your products need particular staging, tell us during consultation so we can plan it.": "Ya, kami jalankan sesi dari setup kami sendiri di Johor Bahru, termasuk pencahayaan dan setup streaming. Jika produk anda memerlukan staging tertentu, beritahu kami semasa konsultasi supaya kami boleh rancang lebih awal.",
  "Your PDPA rights": "Hak PDPA anda",
  "in preparation": "dalam persediaan",
  "1 session per week": "1 sesi seminggu",
  "12 assets + short-form edits": "12 aset + suntingan short-form",
  "2 creative assets per month (covers, overlays)": "2 aset kreatif sebulan (cover, overlay)",
  "24 July 2026": "24 Julai 2026",
  "3 sessions per week": "3 sesi seminggu",
  "4. A reason to stay. Lives reward duration — a giveaway at the hour mark, a second drop, a discount that unlocks at a viewer count. Give people a reason not to scroll away.": "4. Sebab untuk terus menonton. Live memberi ganjaran kepada tempoh — giveaway pada penanda satu jam, drop kedua, diskaun yang terbuka pada jumlah penonton tertentu. Beri penonton sebab untuk tidak scroll pergi.",
  "5. A way to measure. Decide before the session what success means: GMV, new followers, average watch time. A first live is a baseline, not a verdict — but only if you record the numbers.": "5. Cara untuk mengukur. Tetapkan sebelum sesi apa maksud kejayaan: GMV, pengikut baharu, purata masa tontonan. Live pertama ialah garis asas, bukan keputusan muktamad — tetapi hanya jika anda merekod nombornya.",
  "A Consultancy Service by A2Z Creative Marketing. Advice from a team that runs live channels and campaigns every week — so what you get is a plan that has already survived contact with real buyers.": "Perkhidmatan Perundingan oleh A2Z Creative Marketing. Nasihat daripada pasukan yang mengendalikan channel live dan campaign setiap minggu — jadi apa yang anda dapat ialah pelan yang sudah teruji dengan pembeli sebenar.",
  "A read of what your channels are actually producing — reach, conversion, GMV, cost per sale — and a prioritised list of what to fix first, in the order that pays back fastest.": "Bacaan tentang apa yang channel anda hasilkan sebenarnya — reach, conversion, GMV, kos setiap jualan — dan senarai keutamaan apa yang perlu dibaiki dahulu, mengikut urutan yang paling cepat memberi pulangan.",
  "A session is a sales format, not a camera pointed at products. We bring a trained host and a rundown built around your best offers — pitch, answer, close, on repeat for the full session.": "Sesi ialah format jualan, bukan kamera yang dihalakan ke arah produk. Kami bawa host terlatih dan rundown yang dibina sekitar tawaran terbaik anda — pitch, jawab, close, berulang sepanjang sesi.",
  "A2Z CREATIVE MARKETING is a growing creative marketing team based in Johor Bahru, working across brand and campaign creative, digital marketing, content production, live commerce, and consultancy. We don't always have open roles listed — but we are always interested in meeting people who can sell, produce, or create.": "A2Z CREATIVE MARKETING ialah pasukan pemasaran kreatif yang sedang berkembang di Johor Bahru, bergerak dalam kreatif jenama dan campaign, pemasaran digital, penerbitan content, live commerce, dan perundingan. Kami tidak sentiasa menyenaraikan jawatan kosong — tetapi kami sentiasa berminat untuk bertemu orang yang boleh menjual, menerbit, atau mencipta.",
  "A2Z Creative Marketing office location on Google Maps": "Lokasi pejabat A2Z Creative Marketing di Google Maps",
  "AZ ONE OFFICIAL is A2Z Creative Marketing's consultancy service — the business unit brand owners engage for business consultation, live commerce consultancy, and brand and channel strategy. It is a separate registered entity (202603168673 / JM1046169-H) and the entity that issues consultancy quotations, invoices, and receipts. See our Consultancy page for what an engagement covers.": "AZ ONE OFFICIAL ialah perkhidmatan perundingan A2Z Creative Marketing — unit perniagaan yang dilantik pemilik jenama untuk konsultasi perniagaan, perundingan live commerce, serta strategi jenama dan channel. Ia merupakan entiti berdaftar yang berasingan (202603168673 / JM1046169-H) dan entiti yang mengeluarkan sebut harga, invois, dan resit perundingan. Lihat halaman Perundingan kami untuk mengetahui apa yang termasuk dalam setiap engagement.",
  "About": "Tentang Kami",
  "Ask us directly on WhatsApp": "Tanya kami terus di WhatsApp",
  "Bi-weekly strategy call": "Strategy call dua minggu sekali",
  "Book a strategy call": "Tempah strategy call",
  "Brand positioning, pricing, channel strategy, and new product development — delivered by AZ ONE OFFICIAL, our consultancy service, and advised from the seller's chair.": "Positioning jenama, penetapan harga, strategi channel, dan pembangunan produk baharu — disampaikan oleh AZ ONE OFFICIAL, perkhidmatan perundingan kami, dan dinasihatkan dari kerusi penjual.",
  "Build brands with us": "Bina jenama bersama kami",
  "Business & product development": "Pembangunan perniagaan & produk",
  "Can I use my own host?": "Boleh saya guna host sendiri?",
  "Case Studies": "Kajian Kes",
  "Channel positioning, campaign planning, and a content calendar across TikTok, Instagram, and Facebook — built to feed your sales channels instead of fighting them.": "Positioning channel, perancangan campaign, dan kalendar content merentasi TikTok, Instagram, dan Facebook — dibina untuk menyokong saluran jualan anda, bukan melawannya.",
  "Compare packages": "Banding pakej",
  "Consultation": "Konsultasi",
  "Content creation & video": "Penciptaan content & video",
  "Creative marketing, digital marketing, content, live commerce, and consultancy. Pick a single service or hand us the whole thing — every engagement starts with a free consultation, so we recommend only what your brand actually needs.": "Pemasaran kreatif, pemasaran digital, content, live commerce, dan perundingan. Pilih satu perkhidmatan atau serahkan semuanya kepada kami — setiap engagement bermula dengan konsultasi percuma, jadi kami hanya cadangkan apa yang jenama anda betul-betul perlukan.",
  "Creatives, hosts, and management in one team you can meet — with fast WhatsApp support during your campaigns and sessions.": "Kreatif, host, dan pengurusan dalam satu pasukan yang boleh anda temui — dengan sokongan WhatsApp pantas sepanjang campaign dan sesi anda.",
  "Custom schedule": "Jadual custom",
  "Dedicated account lead": "Account lead khusus",
  "Digital marketing": "Pemasaran digital",
  "Do you provide a studio?": "Adakah anda sediakan studio?",
  "Everything a brand needs to grow": "Semua yang jenama perlukan untuk berkembang",
  "Fast support": "Sokongan pantas",
  "Follow us": "Ikuti kami",
  "From first call to first sale": "Dari panggilan pertama ke jualan pertama",
  "Get a free live audit": "Dapatkan audit live percuma",
  "Governing law": "Undang-undang yang mentadbir",
  "Host rotation + dedicated live manager": "Rotasi host + live manager khusus",
  "How A2Z Creative Marketing grows brand sales — challenge, approach, result.": "Bagaimana A2Z Creative Marketing meningkatkan jualan jenama — cabaran, pendekatan, hasil.",
  "How much does it cost?": "Berapa kosnya?",
  "In-app checkout, vouchers, and shop campaigns": "Checkout dalam app, baucar, dan campaign kedai",
  "Introduce yourself on WhatsApp with a short intro, a portfolio or showreel if you have one, and for hosts any on-camera clip.": "Perkenalkan diri anda di WhatsApp dengan intro ringkas, portfolio atau showreel jika ada, dan bagi host sertakan sebarang klip depan kamera.",
  "Join A2Z Creative Marketing — live hosts, live operations, creative, and digital marketing roles in Johor Bahru.": "Sertai A2Z Creative Marketing — jawatan live host, live operations, kreatif, dan pemasaran digital di Johor Bahru.",
  "Live commerce management": "Pengurusan live commerce",
  "Live operations — moderation, order handling, session support": "Live operations — moderasi, pengendalian pesanan, sokongan sesi",
  "Login": "Log Masuk",
  "Moderation, order push, and offer pacing handled in real time while the host sells.": "Moderasi, order push, dan pacing tawaran diuruskan secara real time sementara host menjual.",
  "Most brands don't stall because the product is wrong — they stall on the parts nobody warned them about, from an identity that never settles to a live room that draws a crowd and sells nothing. These are the ones we get hired for.": "Kebanyakan jenama tidak tersekat kerana produknya salah — mereka tersekat pada bahagian yang tiada siapa beritahu awal-awal, dari identiti yang tidak pernah mantap sehinggalah live room yang menarik ramai penonton tetapi tidak menjual apa-apa. Inilah masalah yang kami diupah untuk selesaikan.",
  "No guarantee of results": "Tiada jaminan hasil",
  "Not included": "Tidak termasuk",
  "On-site sessions": "Sesi di lokasi anda",
  "One WhatsApp away. Questions answered in hours, not ticket queues.": "Sekadar satu WhatsApp. Soalan dijawab dalam beberapa jam, bukan dalam barisan tiket.",
  "Or send a message": "Atau hantar mesej",
  "Our core platform is TikTok Live, where Malaysian live commerce is strongest today. We can also support other platforms your brand already sells on — tell us during consultation.": "Platform utama kami ialah TikTok Live, di mana live commerce Malaysia paling kuat hari ini. Kami juga boleh menyokong platform lain yang jenama anda sudah gunakan untuk berjual — beritahu kami semasa konsultasi.",
  "Packages": "Pakej",
  "Post-session report": "Laporan selepas sesi",
  "Practical notes on marketing and live commerce in Malaysia from the A2Z Creative Marketing team.": "Nota praktikal tentang pemasaran dan live commerce di Malaysia daripada pasukan A2Z Creative Marketing.",
  "Products, pricing, and stock. We handle the rest: rundown, studio, host, moderation, and reporting.": "Produk, harga, dan stok. Kami uruskan selebihnya: rundown, studio, host, moderasi, dan pelaporan.",
  "Read more →": "Baca lagi →",
  "Reporting turns into the next campaign and the next rundown. We keep what converted, cut what didn't, and grow the schedule.": "Pelaporan bertukar menjadi campaign seterusnya dan rundown seterusnya. Kami kekalkan apa yang convert, buang apa yang tidak, dan kembangkan jadual.",
  "Same post-live reporting: GMV, viewers, conversion": "Pelaporan selepas live yang sama: GMV, penonton, conversion",
  "See all services": "Lihat semua perkhidmatan",
  "Services": "Perkhidmatan",
  "Sharing": "Perkongsian",
  "Sound familiar?": "Kedengaran biasa?",
  "Strategists, designers, producers, and hosts who treat every brief like a campaign, not a favour done between other jobs.": "Ahli strategi, pereka, penerbit, dan host yang melayan setiap brief seperti satu campaign, bukan bantuan sambil lewa antara kerja lain.",
  "Terms &amp; Conditions": "Terma &amp; Syarat",
  "The best proof of live commerce is a live session. Catch us on TikTok or Shopee while we run one — or watch our latest sessions and cuts right here.": "Bukti terbaik live commerce ialah sesi live itu sendiri. Ikuti kami di TikTok atau Shopee semasa kami menjalankan satu sesi — atau tonton sesi dan cut terbaharu kami di sini.",
  "The problems we get hired to solve": "Masalah yang kami diupah untuk selesaikan",
  "Trained host + producer on every live": "Host terlatih + producer pada setiap live",
  "Views are fine, but conversion is not": "Views memang okey, tapi conversion tidak",
  "Watch on Shopee Live": "Tonton di Shopee Live",
  "We are a Malaysian creative marketing group: creative marketing, digital marketing, content creation, live commerce, marketing consultancy, and business and product development. Brands come to us for one of those and usually stay for two or three, because the same team runs the strategy, the creative, and the selling.": "Kami sebuah kumpulan pemasaran kreatif Malaysia: pemasaran kreatif, pemasaran digital, penciptaan content, live commerce, perundingan pemasaran, dan pembangunan perniagaan dan produk. Jenama datang kepada kami untuk salah satu daripadanya dan biasanya kekal untuk dua atau tiga, kerana pasukan yang sama mengendalikan strategi, kreatif, dan jualan.",
  "We review your products, margins, audience, and current marketing, and agree on what growth actually looks like for you.": "Kami semak produk, margin, audiens, dan pemasaran semasa anda, dan bersetuju tentang rupa sebenar pertumbuhan bagi anda.",
  "We went live and nobody bought": "Kami buat live tapi tiada siapa membeli",
  "Weekly reporting + optimisation review": "Pelaporan mingguan + semakan optimisation",
  "What does A2Z Creative Marketing actually do?": "Apa sebenarnya yang A2Z Creative Marketing buat?",
  "What we advise on": "Apa yang kami nasihatkan",
  "WhatsApp us now": "WhatsApp kami sekarang",
  "Why brands choose us": "Kenapa jenama pilih kami",
  "Yes. Good marketing rewards good products and good offers, not big ad budgets. Our packages scale from single trial sessions to full monthly schedules.": "Ya. Pemasaran yang baik memberi ganjaran kepada produk dan tawaran yang baik, bukan bajet iklan yang besar. Pakej kami boleh diskalakan dari sesi percubaan tunggal sehingga jadual bulanan penuh.",
  "Your next customer is already watching someone sell. Make it you.": "Pelanggan anda yang seterusnya sedang menonton orang lain menjual. Jadikan ia anda.",
  "is this account live now?": "adakah akaun ini sedang live sekarang?",
  "1 trained host": "1 host terlatih",
  "12 creative assets + short-form edits": "12 aset kreatif + suntingan short-form",
  "2 hours": "2 jam",
  "2–3 hours": "2–3 jam",
  "3. Answers to the ten questions you'll definitely get. Size, material, delivery time, COD or not, returns. Write them down. A host who hesitates on basics loses the room.": "3. Jawapan kepada sepuluh soalan yang pasti anda terima. Saiz, bahan, tempoh penghantaran, COD atau tidak, pemulangan. Tuliskan semuanya. Host yang teragak-agak pada perkara asas akan hilang perhatian penonton.",
  "5 per week": "5 setiap minggu",
  "500+ sessions": "500+ sesi",
  "A free first call on WhatsApp to understand the business and decide whether we are the right people for it.": "Panggilan pertama percuma di WhatsApp untuk memahami perniagaan anda dan menentukan sama ada kami orang yang tepat untuknya.",
  "A real schedule, so the algorithm and your buyers learn to expect you.": "Jadual yang konsisten, supaya algoritma dan pembeli anda tahu bila untuk menunggu anda.",
  "A written recommendation, a prioritised action plan, and an optional review after you have run with it.": "Cadangan bertulis, pelan tindakan mengikut keutamaan, dan semakan pilihan selepas anda melaksanakannya.",
  "A2Z Creative Marketing — 202603003468 (CA0414729-A). A registered Malaysian company, not a freelance side project.": "A2Z Creative Marketing — 202603003468 (CA0414729-A). Syarikat Malaysia yang berdaftar, bukan projek sampingan freelance.",
  "AZ ONE OFFICIAL is the consultancy service of A2Z Creative Marketing. Where the rest of the group builds and runs campaigns and live channels for brands, this is where brand owners come for the decision before the work: what to sell, where to sell it, at what price, and whether a channel is worth entering at all.": "AZ ONE OFFICIAL ialah perkhidmatan perundingan A2Z Creative Marketing. Jika bahagian lain kumpulan ini membina dan mengendalikan campaign serta saluran live untuk jenama, di sinilah pemilik jenama datang untuk keputusan sebelum kerja bermula: apa yang hendak dijual, di mana hendak dijual, pada harga berapa, dan sama ada sesuatu saluran itu berbaloi dimasuki langsung.",
  "About A2Z": "Tentang A2Z",
  "Bahasa Melayu & English hosts": "Host Bahasa Melayu & English",
  "Both. Our hosts sell comfortably in Bahasa Melayu, English, or a natural mix — matched to your audience.": "Kedua-duanya. Host kami selesa menjual dalam Bahasa Melayu, English, atau campuran yang natural — disesuaikan dengan audiens anda.",
  "Brands we run live for": "Jenama yang kami kendalikan live",
  "Building a live channel for a premium modestwear label": "Membina saluran live untuk jenama modestwear premium",
  "Business consultation": "Perundingan perniagaan",
  "Can you come to my office or warehouse?": "Boleh anda datang ke pejabat atau gudang saya?",
  "Challenge": "Cabaran",
  "Clients": "Pelanggan",
  "Compare side by side": "Banding sebelah-menyebelah",
  "Contact": "Hubungi",
  "Creative": "Kreatif",
  "Creative marketing, digital marketing, live commerce management, live host service, content creation and video, plus consultancy and business development.": "Pemasaran kreatif, digital marketing, pengurusan live commerce, perkhidmatan live host, penghasilan content dan video, serta perundingan dan pembangunan perniagaan.",
  "Customer accounts &amp; enquiries": "Akaun &amp; pertanyaan pelanggan",
  "Dedicated host team": "Pasukan host khusus",
  "Digital marketing — social strategy, campaign planning, paid and organic": "Digital marketing — strategi sosial, perancangan campaign, paid dan organik",
  "Do you work with small brands?": "Adakah anda bekerjasama dengan jenama kecil?",
  "Everything dies when the stream ends": "Semuanya mati sebaik sahaja stream tamat",
  "Feature": "Ciri",
  "Full creative production": "Produksi kreatif penuh",
  "Get a free live audit. It is a short call on WhatsApp where we review your products and current channel, then recommend the right starting package.": "Dapatkan audit live percuma. Ia satu panggilan ringkas di WhatsApp di mana kami menyemak produk dan saluran semasa anda, kemudian mengesyorkan pakej permulaan yang tepat.",
  "Host rotation + live manager": "Rotasi host + live manager",
  "How an engagement works": "Bagaimana kerjasama ini berjalan",
  "How we package this": "Bagaimana kami menyusun pakej ini",
  "Included": "Termasuk",
  "It is a separate registered entity — 202603168673 (JM1046169-H) — and the entity that contracts, quotes, and invoices consultancy engagements. Everything else about it is A2Z: the same operators, the same standards, the same numbers.": "Ia entiti berdaftar yang berasingan — 202603168673 (JM1046169-H) — dan entiti yang mengikat kontrak, mengeluarkan sebut harga, dan menginvois kerja perundingan. Selain itu, semuanya A2Z: operator yang sama, standard yang sama, nombor yang sama.",
  "Legal": "Perundangan",
  "Live as a primary sales channel, managed end to end.": "Live sebagai saluran jualan utama, diuruskan dari hujung ke hujung.",
  "Live commerce packages from A2Z Creative Marketing — Starter, Growth, Scale, and Enterprise. Hours, live hosts, reporting, creative, and consultation for Malaysian brands selling on TikTok Live.": "Pakej live commerce daripada A2Z Creative Marketing — Starter, Growth, Scale, dan Enterprise. Jam siaran, live host, pelaporan, kreatif, dan perundingan untuk jenama Malaysia yang menjual di TikTok Live.",
  "Live host + comment moderator": "Live host + moderator komen",
  "Live session, simulated view": "Sesi live, paparan simulasi",
  "Main": "Utama",
  "Modern live studio": "Studio live moden",
  "Most consultancies advise on live commerce from a deck. We run live sessions ourselves, every week, on the same platforms and against the same algorithm you are up against — including for a premium modestwear label whose channel we built from zero and still operate end to end.": "Kebanyakan firma perundingan menasihati tentang live commerce daripada sekeping deck. Kami sendiri menjalankan sesi live, setiap minggu, di platform yang sama dan berdepan algoritma yang sama seperti anda — termasuk untuk sebuah jenama modestwear premium yang salurannya kami bina dari kosong dan masih kami kendalikan dari hujung ke hujung.",
  "No mystery, no vanity metrics. Every live session is planned, produced, and reported like a campaign.": "Tiada misteri, tiada vanity metrics. Setiap sesi live dirancang, dihasilkan, dan dilaporkan seperti sebuah campaign.",
  "Not sure which tier fits?": "Tidak pasti tier mana yang sesuai?",
  "On-site sessions at your office or studio": "Sesi di lokasi anda — pejabat atau studio",
  "One creative direction, applied everywhere: identity, campaign visuals, product cards, session overlays, and packaging cues. A brand a buyer recognises in half a second is a brand they trust enough to buy from.": "Satu hala tuju kreatif, digunakan di semua tempat: identiti, visual campaign, kad produk, overlay sesi, dan elemen pembungkusan. Jenama yang dikenali pembeli dalam masa setengah saat ialah jenama yang cukup dipercayai untuk dibeli.",
  "Our brand looks different everywhere it appears": "Jenama kami nampak berbeza di setiap tempat ia muncul",
  "Our live commerce service is sold in four tiers. Creative, digital marketing, and consultancy are scoped per brief instead — ask us and we will quote them alongside. Every engagement starts with a free live audit: we look at your products and your current channels, then recommend a tier. Pricing is quoted per brand, so you only pay for the cadence and creative you actually use.": "Perkhidmatan live commerce kami dijual dalam empat tier. Kreatif, digital marketing, dan perundingan pula diskopkan mengikut brief — tanya kami dan kami akan sebut harga sekali. Setiap kerjasama bermula dengan audit live percuma: kami tinjau produk dan saluran semasa anda, kemudian syorkan satu tier. Harga disebut mengikut jenama, jadi anda hanya bayar untuk cadence dan kerja kreatif yang benar-benar anda guna.",
  "Payments and cancellations": "Pembayaran dan pembatalan",
  "Positioning and creative direction first, then the machinery: account readiness, campaign assets, studio setup, host casting, and a session rundown built around your best offers.": "Positioning dan hala tuju kreatif dahulu, kemudian jentera kerjanya: kesediaan akaun, aset campaign, persediaan studio, pemilihan host, dan rundown sesi yang dibina sekitar tawaran terbaik anda.",
  "Post-session report: viewers, orders, GMV": "Laporan selepas sesi: penonton, pesanan, GMV",
  "Pricing depends on how often you go live, how many hosts you need, and how much creative work is involved — so we quote per brand rather than publish a rate card. Our packages start with one session a week and scale to a daily schedule. Tell us your products and target cadence on WhatsApp and you'll get a clear number, not a range.": "Harga bergantung pada berapa kerap anda live, berapa ramai host yang anda perlukan, dan sebanyak mana kerja kreatif yang terlibat — jadi kami sebut harga mengikut jenama dan bukannya menerbitkan rate card. Pakej kami bermula dengan satu sesi seminggu dan boleh ditingkatkan kepada jadual harian. Beritahu kami produk dan cadence sasaran anda di WhatsApp dan anda akan dapat angka yang jelas, bukan julat.",
  "Professional team": "Pasukan profesional",
  "Ready when you are": "Sedia bila anda sedia",
  "Result": "Hasil",
  "See our consultancy": "Lihat perkhidmatan perundingan kami",
  "Session rundown built around your best offers": "Rundown sesi yang dibina sekitar tawaran terbaik anda",
  "Shoots, short-form edits, and live-session highlights cut into content that keeps selling long after the stream ends.": "Penggambaran, suntingan short-form, dan highlight sesi live disunting menjadi content yang terus menjual lama selepas stream tamat.",
  "Staff personal data": "Data peribadi kakitangan",
  "Team & capability building": "Pembinaan pasukan & keupayaan",
  "Terms governing the use of the A2Z Creative Marketing website and services.": "Terma yang mengawal penggunaan laman web dan perkhidmatan A2Z Creative Marketing.",
  "The brand sells premium chiffon in a category where the decision is tactile — drape, weight, and true colour decide the sale, and none of them survive a flat product photo. It had product and a point of view, but no live presence, no host, and no repeatable session format.": "Jenama ini menjual chiffon premium dalam kategori yang keputusannya bersifat sentuhan — jatuh kain, berat, dan warna sebenar yang menentukan jualan, dan tiada satu pun daripadanya terserlah dalam gambar produk yang rata. Ia ada produk dan ada pendirian, tetapi tiada kehadiran live, tiada host, dan tiada format sesi yang boleh diulang.",
  "The questions brands ask us most, answered straight.": "Soalan yang paling kerap ditanya jenama, dijawab terus terang.",
  "To improve this website and our services.": "Untuk menambah baik laman web ini dan perkhidmatan kami.",
  "Trained hosts who sell — product pitching, pinned-deal pacing, and comment conversion, in Bahasa Melayu and English.": "Host terlatih yang benar-benar menjual — pitching produk, pacing pinned deal, dan menukar komen kepada jualan, dalam Bahasa Melayu dan English.",
  "Visit us": "Kunjungi kami",
  "Watch us live on TikTok": "Tonton kami live di TikTok",
  "We built and run the live selling channel for a premium modestwear label end to end — so every recommendation comes from the seller's chair.": "Kami bina dan kendalikan saluran jualan live untuk sebuah jenama modestwear premium dari hujung ke hujung — jadi setiap syor datang dari kerusi penjual.",
  "We run channels, not just campaigns: for a premium modestwear label we built the live selling channel from zero and operate it end to end. When we advise you, it is from the seller's chair, not the sidelines.": "Kami kendalikan saluran, bukan sekadar campaign: untuk sebuah jenama modestwear premium, kami bina saluran jualan live dari kosong dan mengendalikannya dari hujung ke hujung. Bila kami menasihati anda, ia dari kerusi penjual, bukan dari tepi gelanggang.",
  "We&apos;re always interested in": "Kami sentiasa berminat dengan",
  "Weekly reporting with what we change next": "Laporan mingguan berserta apa yang kami ubah seterusnya",
  "What is AZ ONE OFFICIAL?": "Apa itu AZ ONE OFFICIAL?",
  "Whether live suits your product, what a viable session cadence costs, how to cast and train hosts, and what to measure. Includes an honest answer when live is the wrong channel for you.": "Sama ada live sesuai untuk produk anda, berapa kos cadence sesi yang berdaya maju, bagaimana memilih dan melatih host, dan apa yang perlu diukur. Termasuk jawapan jujur apabila live bukan saluran yang betul untuk anda.",
  "Work that sells, live": "Kerja yang menjual, secara live",
  "Yes. If you already have a host or an in-house team, we can run everything around them — rundown, moderation, offers, order push, and reporting — or train them on the selling techniques our hosts use. Some brands start with our host and transition to their own later.": "Ya. Jika anda sudah ada host atau pasukan dalaman, kami boleh kendalikan segalanya di sekeliling mereka — rundown, moderasi, tawaran, order push, dan pelaporan — atau melatih mereka dengan teknik jualan yang digunakan host kami. Ada jenama yang bermula dengan host kami dan beralih kepada host sendiri kemudian.",
  "Your rights": "Hak anda",
  "an agency with zero experience": "sebuah agensi tanpa sebarang pengalaman",
  "1 trained live host (BM/English)": "1 host live terlatih (BM/English)",
  "12 hosts": "12 host",
  "2 hours per live session": "2 jam setiap sesi live",
  "2–3 hours per live session": "2–3 jam setiap sesi live",
  "5 sessions per week": "5 sesi seminggu",
  "6 assets / month": "6 aset / bulan",
  "A live channel that runs on a schedule rather than on hope: drops sell in-session, pricing is revealed live to limited quantities, and session footage keeps selling between drops.": "Saluran live yang berjalan mengikut jadual, bukan mengikut harapan: drop dijual dalam sesi, harga didedahkan secara live untuk kuantiti terhad, dan rakaman sesi terus menjual antara satu drop dan drop seterusnya.",
  "A repeatable drop format the brand now runs on a schedule, with short-form content cut from each session keeping the channel warm in between.": "Format drop berulang yang kini dijalankan jenama itu mengikut jadual, dengan content short-form yang dipotong daripada setiap sesi mengekalkan saluran tetap panas di antaranya.",
  "A2Z Creative Marketing is a Malaysian creative marketing group in Johor Bahru — creative and digital marketing, content creation, live commerce, and consultancy under one roof.": "A2Z Creative Marketing ialah kumpulan pemasaran kreatif Malaysia di Johor Bahru — pemasaran kreatif dan digital, penghasilan content, live commerce, dan perundingan di bawah satu bumbung.",
  "AZ ONE OFFICIAL — A Consultancy Service by A2Z Creative Marketing": "AZ ONE OFFICIAL — Perkhidmatan Perundingan oleh A2Z Creative Marketing",
  "About us": "Tentang kami",
  "Based in Johor Bahru, marketing and selling in Bahasa Melayu and English to the audience you actually serve.": "Beroperasi di Johor Bahru, memasarkan dan menjual dalam Bahasa Melayu dan English kepada audiens yang benar-benar anda sasarkan.",
  "Book a free consultation": "Tempah sesi perundingan percuma",
  "Brand & channel strategy": "Strategi jenama & saluran",
  "Brands, campaigns, and live sessions produced by A2Z Creative Marketing.": "Jenama, campaign, dan sesi live yang dihasilkan oleh A2Z Creative Marketing.",
  "Built around your calendar, your studio, and your team.": "Dibina mengikut kalendar, studio, dan pasukan anda.",
  "Campaigns run and sessions go live. Our hosts and producers work the room end to end — pitching, moderating, and pushing orders in real time.": "Campaign berjalan dan sesi live bermula. Host dan produser kami menguruskan semuanya dari mula hingga akhir — pitching, moderasi, dan push order secara real time.",
  "Can you host in Bahasa Melayu and English?": "Boleh host dalam Bahasa Melayu dan English?",
  "Challenge, approach, result": "Cabaran, pendekatan, hasil",
  "Close menu": "Tutup menu",
  "Consultancy": "Perundingan",
  "Contact A2Z Creative Marketing — book a free consultation on WhatsApp or visit us in Johor Bahru.": "Hubungi A2Z Creative Marketing — tempah sesi perundingan percuma melalui WhatsApp atau kunjungi kami di Johor Bahru.",
  "Creative, Digital & Live Commerce Partners": "Rakan Kreatif, Digital & Live Commerce",
  "Custom format": "Format tersuai",
  "Daily or campaign-based scheduling": "Penjadualan harian atau berasaskan campaign",
  "Dedicated host team and account lead": "Pasukan host khusus dan account lead",
  "Do you guarantee sales?": "Adakah anda menjamin jualan?",
  "Empowering brands through creative marketing, digital growth, and live commerce.": "Memperkasa jenama melalui pemasaran kreatif, pertumbuhan digital, dan live commerce.",
  "Explore": "Terokai",
  "Feature comparison across A2Z Creative Marketing live commerce packages": "Perbandingan ciri antara pakej live commerce A2Z Creative Marketing",
  "For brands, the practical difference is measurability. A live session produces hard numbers within hours: viewers, comments, add-to-carts, GMV. You learn more about your offer in one two-hour live than in a month of static posting.": "Bagi jenama, perbezaan praktikalnya ialah ia boleh diukur. Satu sesi live menghasilkan angka konkrit dalam masa beberapa jam: penonton, komen, add-to-cart, GMV. Anda belajar lebih banyak tentang offer anda dalam satu live dua jam berbanding sebulan posting statik.",
  "Full production": "Produksi penuh",
  "Get these five right and even a modest first session becomes a foundation. Get them wrong and no amount of on-camera charm will save it.": "Betulkan lima perkara ini dan sesi pertama yang sederhana pun boleh menjadi asas yang kukuh. Tersilap pula, sebanyak mana pun karisma di depan kamera tidak akan menyelamatkannya.",
  "Hi A2Z Creative Marketing, I'm interested in your services. I would like to know more.": "Hi A2Z Creative Marketing, saya berminat dengan perkhidmatan anda. Saya ingin tahu dengan lebih lanjut.",
  "Hours per session": "Jam setiap sesi",
  "How do I get started?": "Bagaimana untuk saya mula?",
  "How we solve it": "Bagaimana kami selesaikannya",
  "It works because it restores something online shopping removed: a person you can ask. When a viewer types a question and hears the answer seconds later — in their own language, from someone holding the actual product — trust forms faster than any product page can manage.": "Ia berkesan kerana ia mengembalikan sesuatu yang hilang daripada pembelian online: seseorang yang boleh anda tanya. Apabila penonton menaip soalan dan mendengar jawapannya beberapa saat kemudian — dalam bahasa mereka sendiri, daripada seseorang yang sedang memegang produk itu — kepercayaan terbentuk lebih pantas daripada mana-mana product page.",
  "Let's talk about your next live": "Mari bincang tentang live anda yang seterusnya",
  "Live commerce consultancy": "Perundingan live commerce",
  "Live commerce turns a product feed into a conversation. Here's how it works and why Malaysian audiences respond to it so strongly.": "Live commerce menukar product feed menjadi satu perbualan. Inilah cara ia berfungsi dan sebab audiens Malaysia memberi respons yang begitu kuat terhadapnya.",
  "Live host service": "Perkhidmatan live host",
  "Live sessions": "Sesi live",
  "Malaysian audiences have taken to this format especially strongly. Shopping here has always been conversational — pasar malam, bargaining, asking the seller what's good. Live commerce is that same behaviour, moved onto a phone screen.": "Audiens Malaysia menerima format ini dengan sangat baik. Membeli-belah di sini memang sentiasa berbentuk perbualan — pasar malam, tawar-menawar, tanya penjual mana yang bagus. Live commerce ialah kelakuan yang sama, dipindahkan ke skrin telefon.",
  "Monthly reporting": "Laporan bulanan",
  "Most first lives fail in preparation, not on camera. Five things to have ready before you press Go Live.": "Kebanyakan live pertama gagal pada peringkat persediaan, bukan di depan kamera. Lima perkara yang perlu siap sebelum anda tekan Go Live.",
  "No, and we would be careful with anyone who does. Sales depend on your product, pricing, stock, and offer as much as on hosting. What we commit to is the controllable part: trained hosts, a proper rundown, consistent sessions, and honest reporting — including when something isn't working and what we'll change.": "Tidak, dan kami akan berhati-hati dengan sesiapa yang berbuat begitu. Jualan bergantung pada produk, harga, stok, dan offer anda sama seperti ia bergantung pada hosting. Apa yang kami komit ialah bahagian yang boleh dikawal: host terlatih, rundown yang betul, sesi yang konsisten, dan laporan yang jujur — termasuk bila sesuatu tidak berkesan dan apa yang akan kami ubah.",
  "Notes from the live room": "Nota dari live room",
  "Onboarding call": "Panggilan onboarding",
  "Open menu": "Buka menu",
  "Our companies": "Syarikat kami",
  "Our live commerce service is sold in four tiers; creative, digital marketing, and consultancy are scoped per brief. Every engagement starts with a free live audit — we look at your products and current channels, then recommend a tier. Pricing is quoted per brand, so you only pay for the cadence and creative you actually use.": "Perkhidmatan live commerce kami dijual dalam empat tier; kreatif, pemasaran digital, dan perundingan pula ditentukan skopnya mengikut brief. Setiap kerjasama bermula dengan audit live percuma — kami tinjau produk dan saluran anda sekarang, kemudian cadangkan tier yang sesuai. Harga disebut harga mengikut jenama, jadi anda hanya bayar untuk cadence dan kreatif yang benar-benar anda guna.",
  "Performance review": "Semakan prestasi",
  "Positioning, pricing, margin, and offer structure. We start from your numbers, not a template — then agree what a realistic next twelve months looks like and what has to be true for it to happen.": "Positioning, harga, margin, dan struktur offer. Kami mula daripada angka anda, bukan template — kemudian bersetuju tentang rupa dua belas bulan akan datang yang realistik dan apa yang perlu berlaku untuk mencapainya.",
  "Posting is not a strategy. We build the plan first — audience, offer, channel mix, and calendar — then produce content designed to move someone from scroll to checkout, and report on what actually did.": "Posting bukan strategi. Kami bina pelan dahulu — audiens, offer, channel mix, dan kalendar — kemudian hasilkan content yang direka untuk membawa seseorang daripada scroll ke checkout, dan laporkan apa yang benar-benar berkesan.",
  "Privacy Policy": "Polisi Privasi",
  "Purpose-built sets, lighting, and framing that make products look worth buying.": "Set, pencahayaan, dan framing yang dibina khas supaya produk nampak berbaloi dibeli.",
  "Real-time moderation and order push": "Moderasi dan order push secara real-time",
  "Retention and security": "Penyimpanan dan keselamatan",
  "See a live session, live": "Lihat sesi live, secara live",
  "See packages": "Lihat pakej",
  "Sessions scheduled alongside the TikTok calendar": "Sesi dijadualkan seiring dengan kalendar TikTok",
  "Start with the free call": "Mula dengan panggilan percuma",
  "Tell us about your brand, your products, and where you are stuck. If consultancy is not what you need, we will say so and point you at the service that is.": "Ceritakan tentang jenama anda, produk anda, dan di mana anda tersekat. Jika perundingan bukan apa yang anda perlukan, kami akan berterus terang dan tunjukkan perkhidmatan yang sesuai.",
  "Test live commerce properly, without committing a season to it.": "Uji live commerce dengan betul, tanpa perlu komit satu musim penuh.",
  "The catch is that going live badly is worse than not going live at all. An unprepared host, dead air, or fumbled offers cost trust in public. That's the gap agencies close: trained hosts, a session rundown, live operations, and reporting that turns each session into a better next one.": "Masalahnya, buat live dengan buruk lebih teruk daripada tidak buat live langsung. Host yang tidak bersedia, dead air, atau offer yang tersasar merugikan kepercayaan di depan orang ramai. Itulah jurang yang ditutup oleh agensi: host terlatih, rundown sesi, operasi live, dan laporan yang menjadikan setiap sesi lebih baik daripada sesi sebelumnya.",
  "The short version": "Versi ringkasnya",
  "To prepare proposals and manage our engagement with you.": "Untuk menyediakan cadangan dan menguruskan kerjasama kami dengan anda.",
  "Trained to sell in the language your buyers actually shop in, or a natural mix of both.": "Dilatih untuk menjual dalam bahasa yang pembeli anda benar-benar guna semasa membeli-belah, atau gabungan semula jadi kedua-duanya.",
  "Want to see how this applies to your brand?": "Ingin lihat bagaimana ini terpakai kepada jenama anda?",
  "Watch us work": "Lihat kami bekerja",
  "We have no team or time to go live every week": "Kami tiada pasukan atau masa untuk buat live setiap minggu",
  "We run the channel end to end: schedule, studio, host, moderation, order push, and reporting. You approve the plan and the offers; we do the rest, week after week.": "Kami uruskan saluran dari mula hingga akhir: jadual, studio, host, moderasi, order push, dan laporan. Anda luluskan pelan dan offer; kami buat yang selebihnya, minggu demi minggu.",
  "Weekly + optimisation review": "Semakan mingguan + pengoptimuman",
  "What a session with us looks like": "Rupa satu sesi bersama kami",
  "What is live commerce, and why is Malaysia so good at it?": "Apa itu live commerce, dan kenapa Malaysia begitu bagus dalamnya?",
  "WhatsApp support during sessions": "Sokongan WhatsApp semasa sesi",
  "Which platforms deserve your effort, what the brand should stand for on each, and how creative, content, and commerce fit together instead of competing for the same budget.": "Platform mana yang berbaloi dengan usaha anda, apa yang jenama patut wakili pada setiap satu, dan bagaimana kreatif, content, dan commerce bergerak seiring dan bukan bersaing untuk bajet yang sama.",
  "Yes. On-site sessions are available and often make sense when stock is bulky, fragile, or high-value. Travel arrangements are agreed upfront during consultation.": "Ya. Sesi on-site tersedia dan selalunya munasabah apabila stok besar, mudah pecah, atau bernilai tinggi. Urusan perjalanan dipersetujui lebih awal semasa sesi perundingan.",
  "live now?": "live sekarang?",

  /* v1.32.0 — the named portfolio entries */
  "Modestwear brand — live commerce client": "Jenama modestwear — klien live commerce",
  "Business consultancy — sister company": "Perundingan perniagaan — syarikat seinduk",
  "Built the live selling channel from a standing start: session format, trained hosts, rundowns, and the creative that surrounds each drop. We also built and run the brand's own online store.": "Membina saluran jualan live dari kosong: format sesi, host terlatih, rundown, dan kreatif yang mengelilingi setiap drop. Kami juga membina dan mengendalikan kedai dalam talian jenama ini.",
  "A repeatable drop format the brand now runs on a schedule, with short-form content cut from each session keeping the channel warm in between — and a direct-to-customer storefront taking orders between lives.": "Format drop berulang yang kini dijalankan mengikut jadual, dengan kandungan pendek dipotong daripada setiap sesi bagi mengekalkan saluran hangat antara sesi — serta storefront terus kepada pelanggan yang menerima pesanan antara live.",
  "Brand, website and enquiry pipeline for the group's consultancy arm: positioning, the full site, and a lead desk that turns an enquiry into a quotation without anything falling through the gaps.": "Jenama, laman web dan saluran pertanyaan untuk lengan perundingan kumpulan: penentuan kedudukan, laman penuh, dan meja lead yang menukar pertanyaan kepada sebut harga tanpa apa-apa terlepas.",
  "A consultancy that presents as seriously as it works — every enquiry tracked from first message to signed proposal, on its own domain and its own letterhead.": "Firma perundingan yang tampil seserius kerjanya — setiap pertanyaan dijejaki dari mesej pertama hingga cadangan yang ditandatangani, atas domain sendiri dan kepala surat sendiri.",
  "Campaigns, brands, and live sessions produced by A2Z Creative Marketing. Named with each brand’s permission; everyone else stays anonymous.": "Kempen, jenama dan sesi live yang dihasilkan oleh A2Z Creative Marketing. Dinamakan dengan kebenaran setiap jenama; selain itu kekal tanpa nama.",

  /* v1.32.0 second pass — strings found by sweeping the BUILT html,
     which catches the multi-line JSX text nodes a source regex misses. */
  "or its licensors and may not be used without permission. Any client name, mark, or product shown on this site remains the property of that client and is used with permission; nothing here transfers or claims a right in it. Rights in materials produced during an engagement are set out in that engagement's agreement.": "atau pemberi lesennya dan tidak boleh digunakan tanpa kebenaran. Sebarang nama, tanda, atau produk pelanggan yang dipaparkan di laman ini kekal menjadi hak milik pelanggan tersebut dan digunakan dengan kebenaran; tiada apa-apa di sini yang memindahkan atau menuntut sebarang hak ke atasnya. Hak ke atas bahan yang dihasilkan sepanjang sesuatu penugasan dinyatakan dalam perjanjian penugasan tersebut.",
  "(\"A2Z\", \"we\", \"us\") respects your privacy. This policy explains what personal data we collect through this website and our services, how we use it, and the choices you have. We process personal data in line with the Personal Data Protection Act 2010 (PDPA) of Malaysia.": "(\"A2Z\", \"kami\") menghormati privasi anda. Dasar ini menerangkan data peribadi yang kami kumpul melalui laman web ini dan perkhidmatan kami, cara kami menggunakannya, dan pilihan yang ada pada anda. Kami memproses data peribadi selaras dengan Akta Perlindungan Data Peribadi 2010 (PDPA) Malaysia.",
  "We run sessions on Shopee Live too — same rundown, same host discipline, with checkout happening inside Shopee. Open the shop to catch the live badge when a session is running, or browse what we sell between drops.": "Kami turut menjalankan sesi di Shopee Live — rundown yang sama, disiplin host yang sama, dengan proses checkout berlaku di dalam Shopee. Buka kedai untuk melihat lencana live ketika sesi sedang berjalan, atau layari apa yang kami jual antara drop.",
  "To the fullest extent permitted by Malaysian law, our total liability arising from any engagement is limited to the fees paid for that engagement, and we are not liable for indirect or consequential losses.": "Setakat yang dibenarkan sepenuhnya oleh undang-undang Malaysia, jumlah liabiliti kami yang timbul daripada mana-mana penugasan adalah terhad kepada yuran yang telah dibayar bagi penugasan tersebut, dan kami tidak bertanggungjawab ke atas kerugian tidak langsung atau kerugian berbangkit.",
  "Start with a free live audit: we review your products, your brand, and your current channels — then tell you honestly where the growth is and whether live is part of it. No commitment, no pressure.": "Mulakan dengan audit live percuma: kami menilai produk anda, jenama anda, dan saluran semasa anda — kemudian memberitahu anda secara jujur di mana letaknya peluang pertumbuhan dan sama ada live sebahagian daripadanya. Tiada komitmen, tiada paksaan.",
  "We quote per brand rather than publish a rate card, because the right number depends on cadence, hosts, and creative volume. These are the questions we get asked most before that conversation.": "Kami memberikan sebut harga mengikut jenama dan bukannya menerbitkan kad kadar, kerana angka yang tepat bergantung pada kekerapan sesi, host, dan volum kreatif. Inilah soalan yang paling kerap ditanya kepada kami sebelum perbualan itu.",
  "We do not sell your personal data. We share it only with service providers who help us operate (such as hosting and analytics providers), where required by law, or with your consent.": "Kami tidak menjual data peribadi anda. Kami hanya berkongsinya dengan penyedia perkhidmatan yang membantu kami beroperasi (seperti penyedia hosting dan analitik), apabila dikehendaki oleh undang-undang, atau dengan kebenaran anda.",
  "Basic technical data collected automatically when you visit this website, such as pages viewed and approximate location, used in aggregate to understand how the site is used.": "Data teknikal asas yang dikumpul secara automatik apabila anda melawat laman web ini, seperti halaman yang dilihat dan lokasi anggaran, digunakan secara agregat untuk memahami cara laman ini digunakan.",
  "That is what the free live audit is for. Send us your products and we'll tell you honestly whether live is worth it for you — and which tier we'd start you on.": "Itulah tujuan audit live percuma. Hantarkan produk anda kepada kami dan kami akan memberitahu anda secara jujur sama ada live berbaloi untuk anda — dan tier mana yang kami akan mulakan untuk anda.",
  "Contact details you send us — such as your name, company, phone number, and email — when you message us on WhatsApp, email us, or submit an enquiry.": "Butiran perhubungan yang anda hantar kepada kami — seperti nama, syarikat, nombor telefon, dan e-mel anda — apabila anda menghantar mesej kepada kami di WhatsApp, menghantar e-mel, atau mengemukakan pertanyaan.",
  "— we will respond within the timeframes the PDPA prescribes. A Bahasa Malaysia version of this notice is being prepared as the Act requires.": "— kami akan memberikan maklum balas dalam tempoh masa yang ditetapkan oleh PDPA. Versi Bahasa Malaysia bagi notis ini sedang disediakan sebagaimana yang dikehendaki oleh Akta.",
  "Content on this website — including the A2Z CREATIVE MARKETING and AZ ONE OFFICIAL names, logos, text, and images — belongs to": "Kandungan di laman web ini — termasuk nama, logo, teks, dan imej A2Z CREATIVE MARKETING dan AZ ONE OFFICIAL — adalah hak milik",
  "Not live at this moment? The TikTok feed shows our latest sessions and cuts — real hosts, real orders, real reporting.": "Tiada sesi live buat masa ini? Feed TikTok memaparkan sesi dan klip terbaharu kami — host sebenar, pesanan sebenar, pelaporan sebenar.",
  "To send you information about our services, where you have agreed to receive it. You can opt out at any time.": "Untuk menghantar maklumat tentang perkhidmatan kami kepada anda, sekiranya anda telah bersetuju untuk menerimanya. Anda boleh menarik diri pada bila-bila masa.",
  "Prefer writing it down? Send us the details and we'll reply by email or WhatsApp.": "Lebih selesa menulisnya? Hantarkan butirannya kepada kami dan kami akan membalas melalui e-mel atau WhatsApp.",
  "A2Z CREATIVE MARKETING — Creative, Digital & Live Commerce Partners": "A2Z CREATIVE MARKETING — Rakan Kreatif, Digital & Live Commerce",
  "🛒 Offers pinned, moderation live, orders pushed in real time": "🛒 Tawaran dipin, moderasi secara live, pesanan diproses dalam masa nyata",
  "📊 Post-live report: GMV, viewers, conversion, next actions": "📊 Laporan pasca-live: GMV, penonton, kadar penukaran, tindakan seterusnya",
  "Creative marketing, digital growth and live commerce": "Pemasaran kreatif, pertumbuhan digital dan live commerce",
  "💬 \"sis, ada size M tak?\" — answered live, on camera": "💬 \"sis, ada size M tak?\" — dijawab secara live, depan kamera",
  "🎬 Rundown loaded — host and producer on set": "🎬 Rundown sedia — host dan produser di set",
  ", and we work with brands across Malaysia.": ", dan kami bekerjasama dengan jenama di seluruh Malaysia.",
  "Case Studies — A2Z CREATIVE MARKETING": "Kajian Kes — A2Z CREATIVE MARKETING",
  "Consultancy — A2Z CREATIVE MARKETING": "Perundingan — A2Z CREATIVE MARKETING",
  "Packages — A2Z CREATIVE MARKETING": "Pakej — A2Z CREATIVE MARKETING",
  "Careers — A2Z CREATIVE MARKETING": "Kerjaya — A2Z CREATIVE MARKETING",
  "About — A2Z CREATIVE MARKETING": "Tentang Kami — A2Z CREATIVE MARKETING",
  "and we'll map it out together.": "dan kami akan merancangnya bersama anda.",
  "Customer accounts & enquiries": "Akaun & pertanyaan pelanggan",
  "Questions about these terms:": "Soalan tentang terma ini:",
  "Prefer to just message us?": "Lebih suka terus menghantar mesej kepada kami?",
  "Not sure where to start?": "Tidak pasti di mana hendak bermula?",
  "Still have a question?": "Masih ada soalan?",
  "Build the brand.": "Bina jenama.",
  "or via WhatsApp.": "atau melalui WhatsApp.",
  "Case studies": "Kajian kes",
  "Most chosen": "Paling banyak dipilih",
  "on TikTok": "di TikTok",
  "Reporting": "Pelaporan",
  "min read": "min bacaan",
  "Name *": "Nama *",
  "Email": "E-mel",
  "FAQ": "Soalan Lazim",
  "When you create an account or contact us, we process your name, email address, phone number (if provided), your enquiries and our replies, and order information handled through our live commerce operations. Operational staff see the delivery area only — never your street address.": "Apabila anda membuka akaun atau menghubungi kami, kami memproses nama, alamat e-mel, nombor telefon (jika diberikan), pertanyaan anda dan jawapan kami, serta maklumat pesanan yang dikendalikan melalui operasi live commerce kami. Kakitangan operasi hanya melihat kawasan penghantaran — bukan sekali-kali alamat penuh anda.",
  "Marketing and live commerce performance depend on many factors outside our control, including platform algorithms, product pricing, and stock. Unless expressly agreed in writing, we do not guarantee any specific sales, viewership, reach, or growth outcome.": "Prestasi pemasaran dan live commerce bergantung pada banyak faktor di luar kawalan kami, termasuk algoritma platform, harga produk, dan stok. Melainkan dipersetujui secara nyata secara bertulis, kami tidak menjamin sebarang jualan, tontonan, jangkauan, atau hasil pertumbuhan yang tertentu.",
  "Payment terms, cancellation windows, and any refunds are stated in each engagement's proposal or invoice. Booked live sessions cancelled on short notice may be charged, as set out in the applicable proposal.": "Terma pembayaran, tempoh pembatalan, dan sebarang bayaran balik dinyatakan dalam cadangan atau invois bagi setiap penglibatan. Sesi live yang telah ditempah tetapi dibatalkan pada notis singkat boleh dikenakan caj, seperti yang dinyatakan dalam cadangan yang berkenaan.",
  "These services are bundled into four tiers — Starter, Growth, Scale, and Enterprise — so you can start at the cadence that fits and move up when live starts pulling its weight. Pricing is quoted per brand.": "Perkhidmatan ini digabungkan dalam empat tier — Starter, Growth, Scale, dan Enterprise — supaya anda boleh bermula pada kadar yang sesuai dan meningkat naik apabila live mula menunjukkan hasilnya. Harga ditawarkan mengikut setiap jenama.",
  "Under the Personal Data Protection Act 2010 you may request access to and correction of your personal data, and withdraw consent to processing (subject to legal and contractual limits). Write to": "Di bawah Akta Perlindungan Data Peribadi 2010, anda boleh memohon akses kepada dan pembetulan data peribadi anda, serta menarik balik persetujuan terhadap pemprosesan (tertakluk kepada had undang-undang dan kontrak). Sila tulis kepada",
  "Creative marketing, digital marketing, and content production — plus professional live hosts and complete TikTok Live commerce management. One Malaysian team, from the plan to the sale.": "Pemasaran kreatif, pemasaran digital, dan penghasilan content — serta host live profesional dan pengurusan lengkap TikTok Live commerce. Satu pasukan Malaysia, dari perancangan hinggalah ke jualan.",
  "Session footage is cut into short-form content that keeps selling between lives, and every post-live report tells you what converted, what didn’t, and what changes next session.": "Rakaman sesi dipotong menjadi content pendek yang terus menjual antara satu live ke live yang lain, dan setiap laporan pasca-live memberitahu anda apa yang berjaya menukar jualan, apa yang tidak, dan apa yang akan diubah pada sesi seterusnya.",
  "We keep personal data only as long as needed for the purposes above or as required by law, and we take reasonable technical and organisational measures to protect it.": "Kami menyimpan data peribadi hanya selama yang diperlukan bagi tujuan di atas atau seperti yang dikehendaki oleh undang-undang, dan kami mengambil langkah teknikal serta organisasi yang munasabah untuk melindunginya.",
  "Under the PDPA, you may request access to or correction of your personal data, and withdraw consent to its processing. To exercise these rights, contact us at": "Di bawah PDPA, anda boleh memohon akses kepada atau pembetulan data peribadi anda, serta menarik balik persetujuan terhadap pemprosesannya. Untuk melaksanakan hak ini, hubungi kami di",
  "Campaigns, brands, and live sessions produced by A2Z Creative Marketing. Named with each brand\\u2019s permission; everyone else stays anonymous.": "Campaign, jenama, dan sesi live yang dihasilkan oleh A2Z Creative Marketing. Dinamakan dengan kebenaran setiap jenama; selebihnya kekal tanpa nama.",
  "Start with a free live audit — we review your products and current channel, then tell you honestly whether live is worth it for you.": "Mulakan dengan audit live percuma — kami menyemak produk dan saluran semasa anda, kemudian memberitahu anda secara jujur sama ada live berbaloi untuk anda.",
  "We may update this policy from time to time. The latest version will always be published on this page with its updated date.": "Kami mungkin mengemas kini dasar ini dari semasa ke semasa. Versi terkini akan sentiasa diterbitkan di halaman ini berserta tarikh kemas kininya.",
  "These terms are governed by the laws of Malaysia, and the courts of Malaysia have jurisdiction over any dispute.": "Terma ini dikawal oleh undang-undang Malaysia, dan mahkamah Malaysia mempunyai bidang kuasa ke atas sebarang pertikaian.",
  "Business information you share with us during consultations about your brand, products, and sales channels.": "Maklumat perniagaan yang anda kongsikan dengan kami semasa perundingan tentang jenama, produk, dan saluran jualan anda.",
  "This is the rhythm of a managed live: pitch, answer, close — repeated for two hours.": "Inilah rentak sebuah live yang diuruskan: pitch, jawab, tutup jualan — diulang selama dua jam.",
  ". By using this website or engaging our services, you agree to these terms.": ". Dengan menggunakan laman web ini atau menggunakan perkhidmatan kami, anda bersetuju dengan terma ini.",
  "— including pricing, session length, studio, and on-site sessions.": "— termasuk harga, tempoh sesi, studio, dan sesi di lokasi.",
  "📦 Order #214 confirmed while the host styles the next look": "📦 Pesanan #214 disahkan sementara host menyiapkan gaya seterusnya",
  "These terms govern your use of this website, operated by": "Terma ini mengawal penggunaan laman web ini oleh anda, yang dikendalikan oleh",
  "🛒 Pinned: Today-only bundle — checkout in cart": "🛒 Dipin: Bundle hari ini sahaja — checkout dalam troli",
  "Terms & Conditions — A2Z CREATIVE MARKETING": "Terma & Syarat — A2Z CREATIVE MARKETING",
  "Privacy Policy — A2Z CREATIVE MARKETING": "Dasar Privasi — A2Z CREATIVE MARKETING",
  "Business consultancy and development": "Perundingan dan pembangunan perniagaan",
  "Services — A2Z CREATIVE MARKETING": "Perkhidmatan — A2Z CREATIVE MARKETING",
  "Contact — A2Z CREATIVE MARKETING": "Hubungi — A2Z CREATIVE MARKETING",
  "FAQ — A2Z CREATIVE MARKETING": "Soalan Lazim — A2Z CREATIVE MARKETING",
  "We're always interested in": "Kami sentiasa berminat dengan",
  ". All rights reserved.": ". Hak cipta terpelihara.",
  "— where we go live": "— tempat kami buat live",
  "We are based at": "Kami beroperasi di",
  "Last updated:": "Kemas kini terakhir:",
  "Send message": "Hantar mesej",
  "Message *": "Mesej *",
  "Live host": "Host live",
  "Showcase": "Pameran",
  "Company": "Syarikat",
  "Phone": "Telefon",
};
