-- 0093 - v1.63.0: flash sales on the ELFIA store.
--
-- A flash sale is a DEADLINE on the discount an item already carries, not a
-- new category. A product is a bawal or a shawl: that is what it IS, and it
-- does not stop being one because it is on offer this weekend.
--
--   discount set, elfia_flash_until NULL    -> ordinary discount
--   discount set, elfia_flash_until ahead   -> flash sale: pill and countdown
--   discount set, elfia_flash_until passed  -> over. The feed stops applying
--                                              the discount, so the price
--                                              reverts by itself on the next
--                                              scheduled pull.
--
-- The deadline lives here and not on the store because the portal owns the
-- price, so the portal owns when the price changes back. Nobody has to
-- remember to end a sale.
--
-- Stored as an ISO timestamp in UTC. NULL means no flash sale, which is every
-- existing row, so this migration changes no prices and ends no discounts.
--
-- Single ALTER, nothing else in this file (audit B4 rule: one non-idempotent
-- statement per migration, because a half-apply is a no-apply).

ALTER TABLE inventory_items ADD COLUMN elfia_flash_until TEXT;
